### ISSUE TITLE
Default intellisense

### ISSUE THREAD

**Issue by adamhbz** [kleber-swf/vscode-unity-code-snippets#11]
Hi I'm having trouble with the plugin, I've used it before and everything was fine but with new latest install it is preventing the default intenseness showing.

Here is an example where I am creating a new GameObject. With your plugin installed I dont get the intellisense, without it, I get the intellisense.

Heres a shot with it installed:
![screenshot 2019-02-04 at 18 16 16](https://user-images.githubusercontent.com/13640398/52228130-7b9d4800-28a9-11e9-9c8c-2ca40f215ebc.png)
 
And here with it disabled:
![screenshot 2019-02-04 at 18 16 57](https://user-images.githubusercontent.com/13640398/52228166-91127200-28a9-11e9-827f-f1cf5f7dfbad.png)

Thanks

**Comment by kumade** [comment]
Having the same issue, very irritating! And also it would be nice if the snippets were "scoped" so they appear only where they have some sense? For instance, if I'm typing "start" inside a method, I don't want autocompletion to show me a snippet for inserting Unity Start() method, because I'm already writing another method :) The same goes when I'm declaring a variable and trying to autocomplete its name - snippets offer me to insert Unity methods instead of a variable name;

**Comment by kleber-swf** [comment]
I agree!! This is very annoying! This is due a change made in VSCode a while ago about the order the intellisense shows its suggestions: https://code.visualstudio.com/docs/editor/intellisense.

One way to fix it is to alter that order in the settings: https://code.visualstudio.com/docs/editor/intellisense#_settings

**Comment by marquizzo** [comment]
I had to read through the VSCode page to find how to show code completions above the snippets:

**Before:**
![completions1](https://user-images.githubusercontent.com/7864858/97955436-03ec9d80-1d5b-11eb-8229-4a1eb0390b71.png)

**After:**
![completions2](https://user-images.githubusercontent.com/7864858/97955441-06e78e00-1d5b-11eb-8469-b520a041cee0.png)

- Open `File -> Preferences -> Settings`
- In the settings search bar, type "Snippets"
- You'll see a setting labeled `Editor: Snippet Suggestions`. Instead of "Top", select "Bottom".
Now your intellisense should show properties and methods above the code snippets!

@kleber-swf would be super-helpful to put this in the extension details page, cuz finding your comment with the solution took a while!
