### ISSUE TITLE
Add Function Comments Automatically

### ISSUE THREAD

**Issue by davidguerreiro** [kleber-swf/vscode-unity-code-snippets#15]
Would it be great to be able to add  comments or comment tags for functions automatically - something like typing 'summary' and it will create the summary comment structure to comment the function.

Something similar for parameters comments.

Maybe this already exists and I do not know how to use it ?

Many thanks.

**Comment by phindle** [comment]
Have you tried this Extension David?
https://marketplace.visualstudio.com/items?itemName=k--kato.docomment

Cheers.

**Comment by kleber-swf** [comment]
Not everyone use those comments. So it would be nice to have them as an optional feature.

I myself suggested to insert some optional things to the snippets, but it turns out it's impossible without adding steps to create the resultant methods, which would go against the main reason this extension was created: fast development.

I'm open to suggestions though.
