### ISSUE TITLE
Unity methods should be public or protected

### ISSUE THREAD

**Issue by F286** [kleber-swf/vscode-unity-code-snippets#2]
There can be strange shadowing issues if Unity methods such as Start() and Update() are private, if they are defined in a class then also in a subclass only one of them will get called. For this reason they should probably be made public or at least protected.

**Comment by dantonel** [comment]
Actually, I think there should be a setting where you can configure the default visibility, as well as add other modifiers to the default, such as virtual. I would prefer my Unity methods to be "protected virtual" in most cases.

**Comment by kleber-swf** [comment]
Great suggestion!
I'm trying to create the "convention over configuration" pattern here, so the less you need to type when creating things, the better.

But maybe I can let them private by default, but the keyword editable (I think that most of the times (at least in my experience) you want to make them private).

There is not much options in VSCode snippets language, but I'll try to find something nice here.

(Sorry for the delay, I had no notification)

**Comment by kleber-swf** [comment]
Well, turns out we have plenty options to create the methods:
* their access can be `public`, `private` or `protected`
* they can be `virtual` or not
* `Start()` for example can return `void` or `IEnumerator`

The VSCode snippets syntax is very limited and the only thing I could think about was to create options for each of the case, but this made the creation of a new method a long and boring process 😄 .

I created six alternatives to the problem (only for the `Start()` method for now) and I'm open to suggestions. You can help me testing these alternatives opening the csharp snippets file (open command palette (`ctrl+shift+P`) / `Preferences: Configure User Snippets` / `csharp.json (C#)`) and pasting this piece of json:

```json
{
	"Test MonoBehaviour Start 1": {
		"prefix": "start1",
		"description": "Test #1",
		"body": [
			"${1:private} void Start() {",
			"\t$0",
			"}"
		]
	},
	"Test MonoBehaviour Start 2": {
		"prefix": "start2",
		"description": "Test #2",
		"body": [
			"${1|private,protected,public|} void Start() {",
			"\t$0",
			"}"
		]
	},
	"Test MonoBehaviour Start 3": {
		"prefix": "start3",
		"description": "Test #3",
		"body": [
			"${1|private,protected,public|} ${2| ,virtual |}void Start() {",
			"\t$0",
			"}"
		]
	},
	"Test MonoBehaviour Start 4": {
		"prefix": "start4",
		"description": "Test #4",
		"body": [
			"${1|private,protected,public,protected virtual,public virtual|} void Start() {",
			"\t$0",
			"}"
		]
	},
	"Test MonoBehaviour Start 5": {
		"prefix": "start5",
		"description": "Test #5",
		"body": [
			"${1|private,protected,public|} ${2| ,virtual |}${3|void,IEnumerator|} Start() {",
			"\t$0",
			"}"
		]
	},
	"Test MonoBehaviour Start 6": {
		"prefix": "start6",
		"description": "Test #6",
		"body": [
			"${1|private,protected,public,protected virtual,public virtual|} ${2|void,IEnumerator|} Start() {",
			"\t$0",
			"}"
		]
	},
}
```

With that when you start typing `start` the intellisense will suggest all the `start*` options. Use each one and post here which you find out to be the best for your use. If none of them is good for you, please describe what would be the best option for you.

_If you want to go back to the default snippets configuration, just delete all the text you copied from here._

**Comment by kleber-swf** [comment]
I'm reading about vscode extensions lately and maybe I can make some options to this one.
